---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-repo
  namespace: default
spec:
  type: oci
  provider: generic
  url: oci://ghcr.io/prometheus-community/charts/
  interval: 1h
